build libmesa_util_sse41 on all archs
swrast_dri.so had an undefined reference to util_streaming_load_memcpy
on non-x86 archs.

Part of streaming-load-memcpy.c / libmesa_util_sse41.
When USE_SSE41 is not defined, memcpy() is used.

problem noticed at runtime on arm64 by mlarkin@
with and ok tb@